# Generated by Django 2.2.6 on 2021-08-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210803_1902'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_users',
        ),
    ]
